baseurl = "https://slu-soc5050.github.io/"
languageCode = "en-us"
title = "SOC 4930 & SOC 5050"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Christopher Prener, Ph.D."
	description = "SOC 4930 & SOC 5050: Quantiative Analysis - Applied Inferential Statistics"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/slu-soc5050/Core-Documents"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-orange"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "slu-soc5050"
	email   = "chris.prener@slu.edu"


[[menu.main]]
	name   = "About"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Course Resources"
	url    = "course-resources/"
	weight = 2

[[menu.main]]
	name   = "Getting Started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Week 01 - Course Introduction"
	url    = "week-01/"
	weight = 20
	
[[menu.main]]
	name   = "Week 02 - Working with Data (1)"
	url    = "week-02/"
	weight = 21
	
[[menu.main]]
	name   = "Week 03 - Distributions"
	url    = "week-03/"
	weight = 22

[[menu.main]]
	name   = "Week 04 - Probability"
	url    = "week-04/"
	weight = 23
	
[[menu.main]]
	name   = "Week 05 - Random Variables"
	url    = "week-05/"
	weight = 24

[[menu.main]]
	name   = "Week 06 - Inference"
	url    = "week-06/"
	weight = 25

[[menu.main]]
	name   = "Week 07 - Mean Difference (1)"
	url    = "week-07/"
	weight = 26

[[menu.main]]
	name   = "Week 08 - Mean Difference (2)"
	url    = "week-08/"
	weight = 27
	
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]