baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "SLU SOC 4930 & 5050"
theme = "hyde"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/slu-soc5050/"

[[menu.main]]
    name = "Slack"
    url = "https://slu-soc5050.slack.com/"

[[menu.main]]
    name = "Syllabus"
    url = "https://github.com/slu-soc5050/Core-Documents/"

[[menu.main]]
    name = "User's Guide"
    url = "https://slu-soc5050.github.io/User-Guide/index.html"
    
[[menu.main]]
    name = "Wiki"
    url = "https://github.com/slu-soc5050/Core-Documents/wiki/"

[[menu.main]]
    name = "R for Data Science"
    url = "http://r4ds.had.co.nz"
    
[[menu.main]]
    name = "Polls"
    url = "https://pollev.com/chrisprener541"
    
[[menu.main]]
    name = "ShareLaTeX"
    url = "https://www.sharelatex.com/"

[params]
    description = "Quantitative Analysis - Applied Inferential Statistics"
    
    themeColor = "theme-base-0b"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

