baseurl = "https://slu-soc5050.github.io/"
languageCode = "en-us"
title = "SOC 4930 & SOC 5050"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Christopher Prener, Ph.D."
	description = "SOC 4930 & SOC 5050: Quantiative Analysis - Applied Inferential Statistics"
	copyright = "Licensed under a Creative Commons Attribution 4.0 International License"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/slu-soc5050/Core-Documents"

	version = ""
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-orange"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "slu-soc5050"
	email   = "chris.prener@slu.edu"


[[menu.main]]
	name   = "About"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "Course Resources"
	url    = "course-resources/"
	weight = 2

[[menu.main]]
	name   = "Getting Started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Lecture 01 - Course Introduction"
	url    = "lecture-01/"
	weight = 20
	
[[menu.main]]
	name   = "Lecture 02 - Working with Data"
	url    = "lecture-02/"
	weight = 21
	
[[menu.main]]
	name   = "Lecture 03 - Distributions"
	url    = "lecture-03/"
	weight = 22

[[menu.main]]
	name   = "Lecture 04 - Probability"
	url    = "lecture-04/"
	weight = 23
	
[[menu.main]]
	name   = "Lecture 05 - Random Variables"
	url    = "lecture-05/"
	weight = 24

[[menu.main]]
	name   = "Lecture 06 - Inference"
	url    = "lecture-06/"
	weight = 25

[[menu.main]]
	name   = "Lecture 07 - Mean Difference (1)"
	url    = "lecture-07/"
	weight = 26

[[menu.main]]
	name   = "Lecture 08 - Mean Difference (2)"
	url    = "lecture-08/"
	weight = 27

[[menu.main]]
	name   = "Lecture 10 - Correlation (1)"
	url    = "lecture-10/"
	weight = 28
	
[[menu.main]]
	name   = "Lecture 11 - Correlation (2)"
	url    = "lecture-11/"
	weight = 29

[[menu.main]]
	name   = "Lecture 12 - OLS Regression (1)"
	url    = "lecture-12/"
	weight = 30

[[menu.main]]
	name   = "Lecture 13 - OLS Regression (2)"
	url    = "lecture-13/"
	weight = 31
	
[[menu.main]]
	name   = "Lecture 14 - OLS Regression (3)"
	url    = "lecture-14/"
	weight = 32
	
[[menu.main]]
	name   = "Lecture 15 - ANOVA"
	url    = "lecture-15/"
	weight = 33

[[menu.main]]
	name   = "Lecture 16 - Chi-Squared"
	url    = "lecture-16/"
	weight = 34
	
[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40
	
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]